/* eslint-disable */
import { StoryblokStory } from 'storyblok-generate-ts'

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbAccordion {
  has_link_list: boolean
  entries?: SbAccordionEntry[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  _uid: string
  component: 'Accordion'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface Sbrichtext {
  type: string
  content?: Sbrichtext[]
  marks?: Sbrichtext[]
  attrs?: unknown
  text?: string
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbAccordionEntry {
  title?: string
  link_title: string
  body?: Sbrichtext
  _uid: string
  component: 'AccordionEntry'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export type Sbmultilink =
  | {
      id?: string
      cached_url?: string
      anchor?: string
      linktype?: 'story'
      target?: '_self' | '_blank'
    }
  | {
      url?: string
      cached_url?: string
      anchor?: string
      linktype?: 'asset' | 'url'
      target?: '_self' | '_blank'
    }
  | {
      email?: string
      linktype?: 'email'
      target?: '_self' | '_blank'
    }

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbBanner {
  is_active: boolean
  type?: '' | 'info' | 'sale' | 'highlight'
  body?: Sbrichtext
  countdown_until?: string
  links?: SbBannerLink[]
  cta_url?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  scayle_plugin_test?: {
    id?: string
    referenceKey?: string
    name?: string
    imageUrl?: string
  }[]
  item_id: string
  item_name: string
  promotion_id: string
  promotion_name: string
  creative_name: string
  creative_slot: string
  location_id: string
  index: string
  _uid: string
  component: 'Banner'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbBannerLink {
  label?: string
  cta_url?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  _uid: string
  component: 'BannerLink'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbClickableImage {
  item_id?: string
  image: SbCmsImage[]
  cta_url: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ClickableImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface Sbasset {
  _uid?: string
  id: number | null
  alt: string | null
  name: string
  focus: string | null
  source: string | null
  title: string | null
  filename: string
  copyright: string | null
  fieldtype?: string
  meta_data?: null | {}
  is_external_url?: boolean
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbCmsImage {
  desktop_image?: Sbasset
  mobile_image?: Sbasset
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  _uid: string
  component: 'CmsImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbCmsText {
  body?: Sbrichtext
  _uid: string
  component: 'CmsText'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbContentPage {
  teaser_image?: Sbasset
  teaser_image_mobile?: Sbasset
  headline?: string
  subline?: string
  content?: (
    | SbCmsImage
    | SbCmsText
    | SbGrid
    | SbImageSlider
    | SbProductSlider
    | SbSlideShow
    | SbSocialMediaLink
    | SbVideo
    | SbAccordion
    | SbDoubleColumn
    | SbNestedParagraph
    | SbParagraph
  )[]
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  _uid: string
  component: 'ContentPage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbDetailImage {
  image: Sbasset
  product_ids?: string
  _uid: string
  component: 'DetailImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbDoubleColumn {
  column_left?: (
    | SbAccordion
    | SbAccordionEntry
    | SbBanner
    | SbBannerLink
    | SbClickableImage
    | SbCmsImage
    | SbCmsText
    | SbContentPage
    | SbDetailImage
    | SbDoubleColumn
    | SbGrid
    | SbGridTile
    | SbImageSlider
    | SbImageSliderSlide
    | SbImageText
    | SbLink
    | SbLinkGroup
    | SbListingPage
    | SbNestedParagraph
    | SbPage
    | SbParagraph
    | SbProduct
    | SbProductSlider
    | SbShopableImage
    | SbSlide
    | SbSlideShow
    | SbSocialMediaLink
    | SbStory
    | SbTitle
    | SbVideo
  )[]
  column_right?: (
    | SbAccordion
    | SbAccordionEntry
    | SbBanner
    | SbBannerLink
    | SbClickableImage
    | SbCmsImage
    | SbCmsText
    | SbContentPage
    | SbDetailImage
    | SbDoubleColumn
    | SbGrid
    | SbGridTile
    | SbImageSlider
    | SbImageSliderSlide
    | SbImageText
    | SbLink
    | SbLinkGroup
    | SbListingPage
    | SbNestedParagraph
    | SbPage
    | SbParagraph
    | SbProduct
    | SbProductSlider
    | SbShopableImage
    | SbSlide
    | SbSlideShow
    | SbSocialMediaLink
    | SbStory
    | SbTitle
    | SbVideo
  )[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  _uid: string
  component: 'DoubleColumn'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbGrid {
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  is_containered: boolean
  is_containered_desktop: boolean
  is_spaced: boolean
  columns?: (
    | SbShopableImage
    | SbProduct
    | SbClickableImage
    | SbParagraph
    | SbVideo
    | SbCmsImage
    | SbCmsText
    | SbGridTile
    | SbImageText
  )[]
  _uid: string
  component: 'Grid'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbGridTile {
  content: (
    | SbShopableImage
    | SbProduct
    | SbClickableImage
    | SbVideo
    | SbCmsImage
  )[]
  headline?: string
  cta?: string
  cta_link?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  _uid: string
  component: 'GridTile'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbImageSlider {
  headline?: string
  cta_label?: string
  cta_url?: string
  slides?: SbImageSliderSlide[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ImageSlider'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbImageSliderSlide {
  image: Sbasset
  topline?: string
  headline: string
  is_new: boolean
  cta_label: string
  cta_url: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  _uid: string
  component: 'ImageSliderSlide'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbImageText {
  align?: 'start' | 'center' | 'end'
  image: SbCmsImage[]
  topline?: string
  headline?: string
  text?: string
  cta?: string
  cta_link?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  justify?: 'start' | 'center' | 'end'
  _uid: string
  component: 'ImageText'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbLink {
  label: string
  open_in_new_tab: boolean
  cta_url: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  _uid: string
  component: 'Link'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbLinkGroup {
  title?: string
  links?: SbLink[]
  _uid: string
  component: 'LinkGroup'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbListingPage {
  teaser_image?: Sbasset
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  teaser_image_mobile?: Sbasset
  _uid: string
  component: 'ListingPage'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export type Sbmultiasset = {
  alt?: string
  copyright?: string
  id: number
  filename: string
  name: string
  title?: string
}[]

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbNestedParagraph {
  headline?: string
  headline_tag?: '' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  anchor_id?: string
  sub_title?: string
  cta?: Exclude<Sbmultilink, { linktype?: 'asset' }>
  body?: Sbrichtext
  nested_items?: (SbParagraph | SbNestedParagraph)[]
  images?: Sbmultiasset
  background_color?: string
  full_width: boolean
  _uid: string
  component: 'NestedParagraph'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbPage {
  teaser_image?: Sbasset
  teaser_image_mobile?: Sbasset
  content?: (
    | SbCmsImage
    | SbCmsText
    | SbGrid
    | SbImageSlider
    | SbProductSlider
    | SbSlideShow
    | SbSocialMediaLink
    | SbVideo
    | SbAccordion
    | SbDoubleColumn
    | SbNestedParagraph
    | SbParagraph
  )[]
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  _uid: string
  component: 'Page'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbParagraph {
  background_color?: string
  full_width: boolean
  headline?: string
  anchor_id?: string
  cta?: Exclude<Sbmultilink, { linktype?: 'asset' }>
  body?: Sbrichtext
  sub_title?: string
  images?: Sbmultiasset
  _uid: string
  component: 'Paragraph'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbProduct {
  product_id?: string
  _uid: string
  component: 'Product'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbProductSlider {
  headline?: string
  cta_label?: string
  cta_url?: string
  product_ids?: string
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ProductSlider'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbShopableImage {
  image?: SbCmsImage[]
  detail_images?: SbDetailImage[]
  title?: string
  product_ids?: string
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ShopableImage'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbSlide {
  image?: (SbCmsImage | SbVideo)[]
  is_dark: boolean
  align?: 'start' | 'center' | 'end'
  justify?: 'start' | 'center' | 'end'
  topline?: string
  headline?: string
  cta_label?: string
  cta_url?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  _uid: string
  component: 'Slide'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbSlideShow {
  h1?: string
  slides?: SbSlide[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'SlideShow'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbSocialMediaLink {
  type:
    | ''
    | 'facebook'
    | 'instagram'
    | 'snapchat'
    | 'twitter'
    | 'youtube'
    | 'messenger'
    | 'linkedin'
  url?: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  isActive: boolean
  _uid: string
  component: 'SocialMediaLink'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbStory {
  color?: string
  image?: Sbasset
  label?: string
  cta_url?: string
  _uid: string
  component: 'Story'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbTitle {
  text?: string
  image?: Sbasset
  _uid: string
  component: 'Title'
}

/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbVideo {
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  loop: boolean
  control_color?: string
  autoplay: boolean
  has_controls: boolean
  is_containered: boolean
  video: Sbasset
  preview_desktop_image?: Sbasset
  preview_mobile_image?: Sbasset
  _uid: string
  component: 'Video'
}
